spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bus_management_db
    username: anas
    password: madani
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true

server:
  port: 8090