spring.application.name=reservation-viewer-service
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/bus_management_reservation

spring.datasource.username=user_si
spring.datasource.password=1999
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#sql logging
spring.jpa.show-sql=true

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka