spring.application.name=api-gateway
server.port=8765

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

# Configuration CORS globale
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*


# Configuration de la route pour bus-information-service
spring.cloud.gateway.routes[0].id=bus-information-route
spring.cloud.gateway.routes[0].uri=http://localhost:8083
spring.cloud.gateway.routes[0].predicates[0]=Path=/bus-information/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/bus-information/(?<remaining>.*), /$\\{remaining}




#eureka.client.register-with-eureka=false
#spring.cloud.gateway.discovery.locator.enabled=true

