---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: authentification-service
  labels:
    app: authentification-service
spec:
  selector:
    app: authentification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: bus-information-service
  labels:
    app: bus-information-service
spec:
  selector:
    app: bus-information-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: location-service
  labels:
    app: location-service
spec:
  selector:
    app: location-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  labels:
    app: reservation-service
spec:
  selector:
    app: reservation-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-viewer-service
  labels:
    app: reservation-viewer-service
spec:
  selector:
    app: reservation-viewer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
  labels:
    app: service-registry
spec:
  selector:
    app: service-registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
  type: ClusterIP
