spring.application.name=reservation-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/bus_management_reservation
spring.datasource.username=user_si
spring.datasource.password=1999
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.com.microservices.reservationservice=DEBUG

# Show SQL statements
spring.jpa.show-sql=true